version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ws_work_carros
    ports:
      - "3306:3306"
    volumes:
      - ws_work_carros_data:/var/lib/mysql

volumes:
  ws_work_carros_data: